/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mlos_sgl_core_Schewchuck */

#ifndef _Included_mlos_sgl_core_Schewchuck
#define _Included_mlos_sgl_core_Schewchuck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mlos_sgl_core_Schewchuck
 * Method:    schewchuckOrient2d
 * Signature: (DDDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_mlos_sgl_core_Schewchuck_schewchuckOrient2d
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
